# Generated by Django 4.1.7 on 2023-03-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('type', models.CharField(max_length=50, verbose_name='Вид оборудования')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cost', models.CharField(max_length=50, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
            },
        ),
    ]
