# Generated by Django 4.1.7 on 2023-04-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_img', models.ImageField(default='', upload_to='img/')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('ad', models.CharField(max_length=50, verbose_name='Вид')),
                ('full_text', models.TextField(verbose_name='Статья')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'GeneralDocument',
                'verbose_name_plural': 'GeneralDocuments',
            },
        ),
    ]
