# Generated by Django 4.1.7 on 2023-04-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_generaldocument_doc_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaldocument',
            name='model_img',
        ),
        migrations.AlterField(
            model_name='generaldocument',
            name='ad',
            field=models.CharField(max_length=50, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='generaldocument',
            name='full_text',
            field=models.TextField(verbose_name='Текст документа'),
        ),
    ]
