# Generated by Django 4.1.7 on 2023-04-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_remove_generaldocument_model_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldocument',
            name='full_text',
            field=models.TextField(max_length=10000, verbose_name='Текст документа'),
        ),
    ]
