# Generated by Django 4.1.7 on 2023-04-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_alter_generaldocument_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldocument',
            name='full_text',
            field=models.CharField(max_length=10000, verbose_name='Текст документа'),
        ),
    ]
